"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  DIMENSIONS, DOMAINS, PROHIBITED, TIER_META, MAX_SCORE, classify,
} from "./rubric";

const serif = "font-[family-name:var(--font-instrument)]";

const PRESETS = [
  { label: "Chatbot on our website", domain: "service", answers: { decision: "acts", reversible: "effort", sensitivity: "personal", residency: "contracted", subjects: "public", disclosure: "buried", evaluation: "pilot", monitoring: "complaints" } },
  { label: "CV screening tool", domain: "hiring", answers: { decision: "recommend", reversible: "hard", sensitivity: "personal", residency: "vendor", subjects: "public", disclosure: "none", evaluation: "vibes", monitoring: "nothing" } },
  { label: "Drafting newsletter copy", domain: "marketing", answers: { decision: "draft", reversible: "trivial", sensitivity: "internal", residency: "contracted", subjects: "public", disclosure: "clear", evaluation: "pilot", monitoring: "logged" } },
  { label: "Triaging crisis-line messages", domain: "health", answers: { decision: "default", reversible: "no", sensitivity: "special", residency: "consumer", subjects: "vulnerable", disclosure: "none", evaluation: "vibes", monitoring: "nothing" } },
];

export default function Page() {
  const [domain, setDomain] = useState("service");
  const [answers, setAnswers] = useState<Record<string, string>>(PRESETS[0].answers);
  const [flags, setFlags] = useState<string[]>([]);
  const [narrative, setNarrative] = useState("");
  const [loadingN, setLoadingN] = useState(false);

  const result = useMemo(() => classify(domain, answers, flags), [domain, answers, flags]);
  const meta = TIER_META[result.tier];

  function applyPreset(p: (typeof PRESETS)[number]) {
    setDomain(p.domain);
    setAnswers(p.answers);
    setFlags([]);
    setNarrative("");
  }

  async function writePolicy() {
    setLoadingN(true);
    setNarrative("");
    try {
      const res = await fetch("/api/policy", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          domain: DOMAINS.find((d) => d.id === domain)?.label,
          tier: meta.label,
          rationale: result.rationale,
          controls: result.controls.map((c) => `${c.text} (${c.source})`),
        }),
      });
      const data = await res.json();
      setNarrative(data.text || "The drafting service is unavailable. The assessment above is complete without it.");
    } catch {
      setNarrative("The drafting service is unavailable. The assessment above is complete without it.");
    } finally {
      setLoadingN(false);
    }
  }

  const card = "rounded-xl border border-[#E4E7EC] bg-white";
  const pct = Math.round((result.score / MAX_SCORE) * 100);

  return (
    <div className="min-h-screen bg-[#F7F8FA] text-[#101828]">
      <main className="mx-auto max-w-5xl px-6 py-12">
        <Link href="/" className="text-sm text-[#667085] hover:text-[#101828]">← Back to portfolio</Link>

        <h1 className={`${serif} mt-8 text-5xl md:text-6xl`}>AI Governance Sandbox</h1>
        <p className="mt-4 max-w-2xl text-lg text-[#475467]">
          Describe an AI system. Get a risk classification mapped to the EU AI Act, the controls that follow from it,
          and who needs to sign off. The classification is computed from a fixed rubric, not generated by a model —
          the same inputs always produce the same answer.
        </p>

        <div className="mt-8 flex flex-wrap gap-2">
          {PRESETS.map((p) => (
            <button key={p.label} onClick={() => applyPreset(p)}
              className="rounded-full border border-[#D0D5DD] bg-white px-4 py-2 text-sm transition hover:border-[#101828]">
              {p.label}
            </button>
          ))}
        </div>

        <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_380px]">
          {/* ---- Inputs ---- */}
          <div className="grid gap-6">
            <div className={`${card} p-6`}>
              <label className="grid gap-2 text-sm font-medium text-[#344054]">
                Deployment context
                <select value={domain} onChange={(e) => { setDomain(e.target.value); setNarrative(""); }}
                  className="rounded-lg border border-[#D0D5DD] px-4 py-3 text-base outline-none focus:border-[#101828]">
                  {DOMAINS.map((d) => (
                    <option key={d.id} value={d.id}>{d.label}{d.annexIII ? " — Annex III" : ""}</option>
                  ))}
                </select>
              </label>
            </div>

            {DIMENSIONS.map((dim) => (
              <div key={dim.id} className={`${card} p-6`}>
                <h2 className={`${serif} text-2xl`}>{dim.title}</h2>
                <p className="mt-1 text-sm text-[#667085]">{dim.blurb}</p>
                <div className="mt-5 grid gap-5">
                  {dim.questions.map((q) => (
                    <fieldset key={q.id}>
                      <legend className="text-sm font-medium text-[#344054]">{q.prompt}</legend>
                      {q.help && <p className="mt-1 text-xs text-[#98A2B3]">{q.help}</p>}
                      <div className="mt-3 grid gap-2">
                        {q.options.map((o) => {
                          const on = answers[q.id] === o.id;
                          return (
                            <button key={o.id}
                              onClick={() => { setAnswers({ ...answers, [q.id]: o.id }); setNarrative(""); }}
                              className={`rounded-lg border px-4 py-3 text-left text-sm transition ${
                                on ? "border-[#101828] bg-[#101828] text-white" : "border-[#E4E7EC] hover:border-[#98A2B3]"
                              }`}>
                              {o.label}
                            </button>
                          );
                        })}
                      </div>
                    </fieldset>
                  ))}
                </div>
              </div>
            ))}

            <div className={`${card} p-6`}>
              <h2 className={`${serif} text-2xl`}>Prohibited practices</h2>
              <p className="mt-1 text-sm text-[#667085]">
                EU AI Act Art. 5. Any one of these is a hard stop, whatever the rest of the assessment says.
              </p>
              <div className="mt-4 grid gap-2">
                {PROHIBITED.map((p) => {
                  const on = flags.includes(p.id);
                  return (
                    <button key={p.id}
                      onClick={() => { setFlags(on ? flags.filter((f) => f !== p.id) : [...flags, p.id]); setNarrative(""); }}
                      className={`flex items-start gap-3 rounded-lg border px-4 py-3 text-left text-sm transition ${
                        on ? "border-[#B42318] bg-[#FEF3F2]" : "border-[#E4E7EC] hover:border-[#98A2B3]"
                      }`}>
                      <span className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border text-[10px] ${
                        on ? "border-[#B42318] bg-[#B42318] text-white" : "border-[#D0D5DD]"
                      }`}>{on ? "✓" : ""}</span>
                      <span>{p.label} <span className="text-[#98A2B3]">{p.cite}</span></span>
                    </button>
                  );
                })}
              </div>
            </div>
          </div>

          {/* ---- Result ---- */}
          <div className="lg:sticky lg:top-8 lg:self-start">
            <div className={`${card} overflow-hidden`}>
              <div className="p-6" style={{ background: `${meta.color}0F`, borderBottom: `1px solid ${meta.color}33` }}>
                <p className="text-xs font-medium uppercase tracking-widest" style={{ color: meta.color }}>Classification</p>
                <p className={`${serif} mt-2 text-4xl`} style={{ color: meta.color }}>{meta.label}</p>
                <p className="mt-2 text-sm text-[#475467]">{meta.summary}</p>
              </div>

              <div className="p-6">
                {result.tier !== "prohibited" && (
                  <>
                    <div className="flex items-baseline justify-between text-sm">
                      <span className="text-[#667085]">Risk score</span>
                      <span className="font-medium">{result.score} / {MAX_SCORE}</span>
                    </div>
                    <div className="mt-2 h-2 overflow-hidden rounded-full bg-[#F2F4F7]">
                      <div className="h-full rounded-full transition-all" style={{ width: `${pct}%`, background: meta.color }} />
                    </div>
                    <div className="mt-5 grid gap-2">
                      {result.dimensionScores.map((d) => (
                        <div key={d.id} className="flex items-center gap-3 text-sm">
                          <span className="w-28 shrink-0 text-[#667085]">{d.title}</span>
                          <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-[#F2F4F7]">
                            <div className="h-full rounded-full bg-[#344054]" style={{ width: `${(d.score / d.max) * 100}%` }} />
                          </div>
                          <span className="w-10 shrink-0 text-right text-[#98A2B3]">{d.score}/{d.max}</span>
                        </div>
                      ))}
                    </div>
                  </>
                )}

                <h3 className="mt-7 text-xs font-medium uppercase tracking-widest text-[#667085]">Why</h3>
                <ul className="mt-3 grid gap-2 text-sm text-[#475467]">
                  {result.rationale.map((r, i) => <li key={i}>{r}</li>)}
                </ul>

                <h3 className="mt-7 text-xs font-medium uppercase tracking-widest text-[#667085]">Sign-off required</h3>
                <p className="mt-2 text-sm text-[#475467]">{result.approvers.join(" · ")}</p>

                <h3 className="mt-5 text-xs font-medium uppercase tracking-widest text-[#667085]">Review cadence</h3>
                <p className="mt-2 text-sm text-[#475467]">{result.reviewCadence}</p>
              </div>
            </div>
          </div>
        </div>

        {/* ---- Controls ---- */}
        <h2 className={`${serif} mt-16 text-3xl`}>Required controls</h2>
        <p className="mt-2 text-[#667085]">
          {result.controls.length} controls, each traced to the obligation it comes from.
        </p>
        <div className="mt-6 grid gap-3">
          {result.controls.map((c) => (
            <div key={c.id} className={`${card} flex flex-wrap items-start justify-between gap-3 p-5`}>
              <p className="max-w-2xl text-[#101828]">{c.text}</p>
              <div className="flex shrink-0 items-center gap-2">
                <span className="rounded-full bg-[#F2F4F7] px-2.5 py-1 text-xs font-medium text-[#475467]">{c.fn}</span>
                <span className="text-xs text-[#98A2B3]">{c.source}</span>
              </div>
            </div>
          ))}
        </div>

        {/* ---- Optional narrative ---- */}
        <div className="mt-10 rounded-xl border border-[#E4E7EC] bg-white p-6">
          <h2 className={`${serif} text-2xl`}>Policy language</h2>
          <p className="mt-1 text-sm text-[#667085]">
            Turn the assessment into a paragraph you could put in front of a board. The classification above does not
            change — only the prose is generated.
          </p>
          <button onClick={writePolicy} disabled={loadingN}
            className="mt-4 rounded-lg bg-[#101828] px-5 py-3 text-sm font-medium text-white transition hover:bg-[#344054] disabled:opacity-40">
            {loadingN ? "Drafting..." : "Draft policy language"}
          </button>
                   {narrative && (
            <div className="mt-5 grid gap-2 border-l-2 border-[#E4E7EC] pl-5 leading-relaxed text-[#344054]">
              {narrative
                .replace(/\*\*/g, "")
                .split("\n")
                .filter((l) => l.trim())
                .map((l, i) =>
                  l.trim().startsWith("-") ? (
                    <p key={i} className="pl-4 -indent-4">{l.trim()}</p>
                  ) : (
                    <p key={i}>{l.trim()}</p>
                  )
                )}
            </div>
          )}
        </div>

        <section className="mt-16 border-t border-[#E4E7EC] pt-8 text-[#475467]">
          <h2 className="text-xs font-medium uppercase tracking-widest text-[#667085]">Design notes</h2>
          <p className="mt-4 max-w-2xl leading-relaxed">
            The classification is deterministic by design. A governance tool that returns a different tier on a second
            run is worse than no tool, so the rubric is plain code: scored dimensions, plus two hard gates that override
            the score entirely — Art. 5 prohibited practices, and Annex III deployment contexts that are high-risk
            regardless of how carefully the system is built.
          </p>
          <p className="mt-4 max-w-2xl leading-relaxed">
            A language model is used for exactly one thing: rewriting a fixed result as readable prose. It is never
            asked what the risk level is. If the model is unavailable, the assessment is unaffected.
          </p>
          <p className="mt-4 max-w-2xl leading-relaxed text-sm text-[#667085]">
            Educational tool, not legal advice. Citations refer to Regulation (EU) 2024/1689 and the NIST AI Risk
            Management Framework 1.0.
          </p>
        </section>
      </main>
    </div>
  );
}